# -*- coding: utf-8 -*-
"""Vallejo_Daniela_Analizando_EA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AshFR_9-O2SJEBX0ZOD5csq8aWxTEkDB
"""

# scraping_ebay.py
from selenium import webdriver
import time
import pandas as pd
from selenium.webdriver.common.by import By  # Importa By para usar con find_element y find_elements

def main_function():
    # Configuración y scraping de eBay
    driver = webdriver.Chrome()
    driver.get('https://www.ebay.com/sch/i.html?_nkw=smartwatch')

    time.sleep(5)

    productos = []
    precios = []

    while True:
        # Usa By para localizar los elementos
        items = driver.find_elements(By.CSS_SELECTOR, '.s-item__title')  # Actualizado
        prices = driver.find_elements(By.CSS_SELECTOR, '.s-item__price')  # Actualizado
        
        for item, price in zip(items, prices):
            productos.append(item.text)
            precios.append(price.text)

        try:
            # Encuentra el botón "Siguiente" y haz clic
            next_button = driver.find_element(By.CSS_SELECTOR, '.pagination__next')  # Actualizado
            next_button.click()
            time.sleep(5)
        except Exception as e:
            break  # Sale si no hay más páginas

    # Cierra el navegador
    driver.quit()

    # Devuelve los datos en formato DataFrame
    return pd.DataFrame({
        'Producto': productos,
        'Precio': precios
    })
